# Generated by Django 5.0.2 on 2024-02-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_services', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
